# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: tagpr
        uses: Songmu/tagpr@v1
      - name: Adding summary
        run: echo '### ${{steps.tagpr.outputs.tag}}' >> $GITHUB_STEP_SUMMARY
        if: ${{ steps.tagpr.outputs.tag != '' }}
      - name: Checkout
        if: ${{ steps.tagpr.outputs.tag != '' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.tagpr.outputs.tag }}
      - name: Set up Go
        if: ${{ steps.tagpr.outputs.tag != '' }}
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Run GoReleaser
        if: ${{ steps.tagpr.outputs.tag != '' }}
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
